export const memorialDay={
    "2018":[
        {
            date:"2019-1-1",
            lunarDate:'乙亥年九月初一',
            week:"星期日",
            name:'生日',
            desc:"备注",
            daysMatter:{
                logo:'还有',
                num:1
            }
        },
        {
            date:"2019-1-1",
            lunarDate:'乙亥年九月初一',
            week:"星期日",
            name:'生日',
            desc:"备注",
            daysMatter:{
                logo:'还有',
                num:1
            }
        },
    ],
    "2019":[
        {
            date:"2019-1-1",
            lunarDate:'乙亥年九月初一',
            week:"星期日",
            name:'生日',
            desc:"备注",
            daysMatter:{
                logo:'还有',
                num:1
            }
        },
        {
            date:"2019-1-1",
            lunarDate:'乙亥年九月初一',
            week:"星期日",
            name:'生日',
            desc:"备注",
            daysMatter:{
                logo:'还有',
                num:1
            }
        },
    ]
}